import Image from "../src/assets/card.svg";
import Image2 from "../src/assets/card2.jpeg";
import Image3 from "../src/assets/gambarCampaign1.jpg";

const data = [
  {
    id: 1,
    name: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium magnam molestiae praesentium laborum.",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image2,
    category: "Ramadhan",
  },
  {
    id: 2,
    name: "Berbagi Paket  Buka-Sahur untuk Dhuafa & Muslim Palestina",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image,
    category: "Ramadhan",
  },
  {
    id: 3,
    name: "Berbagi Paket  Buka-Sahur untuk Dhuafa & Muslim Palestina",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image3,
    category: "Donasi",
  },
  {
    id: 4,
    name: "Berbagi Paket  Buka-Sahur untuk Dhuafa & Muslim Palestina",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image3,
    category: "Donasi",
  },
  {
    id: 5,
    name: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium magnam molestiae praesentium laborum.",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image2,
    category: "Ramadhan",
  },
  {
    id: 6,
    name: "Berbagi Paket  Buka-Sahur untuk Dhuafa & Muslim Palestina",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image,
    category: "Donasi",
  },
  {
    id: 7,
    name: "Berbagi Paket  Buka-Sahur untuk Dhuafa & Muslim Palestina",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image3,
    category: "Donasi",
  },
  {
    id: 8,
    name: "Berbagi Paket  Buka-Sahur untuk Dhuafa & Muslim Palestina",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image2,
    category: "Donasi",
  },
  {
    id: 9,
    name: "Berbagi Paket  Buka-Sahur untuk Dhuafa & Muslim Palestina ",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image,
    category: "Ramadhan",
  },
  {
    id: 10,
    name: "Berbagi Paket  Buka-Sahur untuk Dhuafa & Muslim Palestina",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image3,
    category: "Donasi",
  },
  {
    id: 11,
    name: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium magnam molestiae praesentium laborum.",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image2,
    category: "Donasi",
  },
  {
    id: 12,
    name: "Berbagi Paket  Buka-Sahur untuk Dhuafa & Muslim Palestina",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image3,
    category: "Donasi",
  },
  {
    id: 13,
    name: "Berbagi Paket  Buka-Sahur untuk Dhuafa & Muslim Palestina",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image,
    category: "Donasi",
  },
  {
    id: 14,
    name: "Berbagi Paket  Buka-Sahur untuk Dhuafa & Muslim Palestina",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image2,
  },
  {
    id: 15,
    name: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium magnam molestiae praesentium laborum.",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image,
    category: "Donasi",
  },
  {
    id: 16,
    name: "Berbagi Paket  Buka-Sahur untuk Dhuafa & Muslim Palestina",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image2,
    category: "Donasi",
  },
  {
    id: 17,
    name: "Berbagi Paket  Buka-Sahur untuk Dhuafa & Muslim Palestina",
    location: "Kota Jakarta Pusat",
    target: 100000000,
    donation: 25000000,
    durasi: "45 Hari Lagi",
    Image: Image3,
    category: "Donasi",
  },
];

export default data;
